name: publish release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build binaries
        run: |
          make all
          ls builds/

      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          name: "DailyGakki"
          files: builds/*